version: 2.1
jobs:
  build:
    machine: true
    steps:
     - run: |
         sudo DEBIAN_FRONTEND=noninteractive apt-get update
         sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libffi-dev libssl-dev python3-dev python3-pyqt5 python3-pyqt5.qtwebengine python3 python3-pip
     - run: pip3 install docker-compose
     - run: sudo usermod -aG docker $USER
     - checkout
     - run: |
         cd ./docker
         echo "UID=$(id -u)" > .env
         echo "GID=$(id -g)" >> .env
         docker-compose up --exit-code-from ubu2204
