version: '3.8'

services:
    ubu1804:
        container_name: ubu1804
        image: ${USER}/ubu1804:ubu1804-20221220
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: "${USER}"
        user: "${USER}"
        stdin_open: true          ## docker run -i
        tty: true                 ## docker run -t
        privileged: true          ## this is a development env!
        environment:
          - USER
        volumes:
          ## folder can be around
          - ~/.gitconfig:/home/$USER/.gitconfig:ro
          #- ~/.ssh:/home/${USER}/.ssh
          ## actually bind mount .ssh to update known_hosts
          - ./workspace:/home/${USER}/workspace
          ## folder must be around
          - type: bind
            source: ~/.ssh
            target: /home/${USER}/.ssh
          - type: bind
            source: ./build_configs
            target: /home/$USER/configs
